packages:
  - playground
  - test/fixtures/*

catalog:
  nuxt: npm:nuxt@^4.5.2
  vue: npm:vue@^3.5.41

minimumReleaseAgeStrict: true

minimumReleaseAgeExclude:
  - 'nuxt'
  - '@nuxt/*'

allowBuilds:
  '@parcel/watcher': false
  'better-sqlite3': true
  cpu-features: false
  esbuild: false
  protobufjs: false
  'sharp@0.34.5': true
  simple-git-hooks: true
  ssh2: false
  vue-demi: false
